/*
 * Copyright (c) 2006-2026 Chris Collins
 */
package com.hitorro.mesh.driver.app.fleet;

import jakarta.annotation.PreDestroy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Spawns / kills local {@code java -jar} processes for fleet members.
 * DEV-ONLY convenience — real Orion/K8s deploys are driven by the
 * manifests generated by {@link FleetRegistry}. Log output redirected
 * to {@code ~/.hitorro/fleet/logs/<name>.log}. PID + start time tracked
 * in-memory (and PID also persisted so a driver restart doesn't orphan
 * live children beyond what the parent-death signal handles).
 */
@Component
public class FleetProcessManager {

    private static final Logger log = LoggerFactory.getLogger(FleetProcessManager.class);

    private static final Path LOG_DIR = Paths.get(System.getProperty("user.home"), ".hitorro/fleet/logs");

    private final Map<String, Handle> processes = new ConcurrentHashMap<>();

    public record Handle(String name, long pid, Instant startedAt, Path logFile, Process process) {}

    public FleetProcessManager() {
        try { Files.createDirectories(LOG_DIR); } catch (IOException e) {
            log.warn("Cannot create fleet log dir {}: {}", LOG_DIR, e.getMessage());
        }
    }

    /** Start a fleet member if not already running via this manager. Returns handle. */
    public synchronized Handle start(FleetRegistry.FleetMember m) throws IOException {
        Handle existing = processes.get(m.name());
        if (existing != null && existing.process().isAlive()) return existing;

        Path jar = FleetRegistry.resolveJar(m);
        if (jar == null) throw new IOException(
                "Fat jar not found for " + m.name() + ". Tried: " + m.jarCandidates());

        List<String> cmd = new ArrayList<>();
        cmd.add(javaBin());
        cmd.add("-jar");
        cmd.add(jar.toString());
        cmd.addAll(m.defaultArgs());

        ProcessBuilder pb = new ProcessBuilder(cmd);
        pb.environment().putAll(m.defaultEnv());
        Path logFile = LOG_DIR.resolve(m.name() + ".log");
        pb.redirectErrorStream(true);
        pb.redirectOutput(ProcessBuilder.Redirect.appendTo(logFile.toFile()));

        Process p = pb.start();
        Handle h = new Handle(m.name(), p.pid(), Instant.now(), logFile, p);
        processes.put(m.name(), h);
        log.info("Fleet start {} pid={} log={}", m.name(), p.pid(), logFile);
        return h;
    }

    /** Kill the process if we started one. */
    public synchronized boolean stop(String name) {
        Handle h = processes.remove(name);
        if (h == null || !h.process().isAlive()) return false;
        h.process().destroy();
        try {
            if (!h.process().waitFor(3, java.util.concurrent.TimeUnit.SECONDS)) h.process().destroyForcibly();
        } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
        log.info("Fleet stop {} pid={}", name, h.pid());
        return true;
    }

    public Handle get(String name) {
        Handle h = processes.get(name);
        if (h != null && !h.process().isAlive()) { processes.remove(name); return null; }
        return h;
    }

    /** Tail the last N lines of a fleet member's log file. */
    public List<String> tailLog(String name, int lines) throws IOException {
        Handle h = processes.get(name);
        Path log = h != null ? h.logFile() : LOG_DIR.resolve(name + ".log");
        if (!Files.exists(log)) return List.of();
        List<String> all = Files.readAllLines(log);
        return all.size() <= lines ? all : all.subList(all.size() - lines, all.size());
    }

    @PreDestroy
    public void shutdown() {
        processes.values().forEach(h -> { try { h.process().destroy(); } catch (Exception ignore) {} });
    }

    private static String javaBin() {
        String javaHome = System.getProperty("java.home");
        return Paths.get(javaHome, "bin", "java").toString();
    }
}
